# .github/workflows/backend.yml
name: Backend CI/CD

on:
  push:
    paths:
      - 'backend/**'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t sagar592/backend-api:latest ./backend
          docker push sagar592/backend-api:latest

      - name: Deploy to Backend EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BACKEND_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull sagar592/backend-api:latest
            docker stop backend-api || true
            docker rm backend-api || true
            docker run -d -p 8000:8000 --name backend-api sagar592/backend-api:latest

