name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  # ЁЯСЗ Uncomment рдХрд░рдиреЗ рдкрд░ рдпрд╣ рдореИрдиреНрдпреБрдЕрд▓ рд░реВрдк рд╕реЗ рднреА trigger рд╣реЛрдЧрд╛
  # workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # ... рдмрд╛рдХреА build-push steps ...

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # ... SSH, deploy commands ...
