jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add servers to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.BACKEND_HOST }} >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.FRONTEND_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Backend
        run: |
          ssh ubuntu@${{ secrets.BACKEND_HOST }} \
            "docker pull ... && docker run ..."

      - name: Deploy Frontend
        run: |
          ssh ubuntu@${{ secrets.FRONTEND_HOST }} \
            "docker pull ... && docker run ..."

